// Schubert (1886): the number of 2-planes in C^5 meeting 6 general 3-planes is
// #SYT(3,3) = deg Gr(2,5) = 5.  A 2x3 rectangle fills with 1..6 in standard order,
// then every standard Young tableau of shape (3,3) is riffled onto a pile (on
// triplet eighths) while an odometer rolls 1 -> 5; the final 5 lands amber on the
// second beat of the card.  The pile then fans out and its five cards light up
// back to front -- the count, once more -- the front card landing on beat three.
// (Checked: the five SYT are 123/456, 124/356, 125/346, 134/256, 135/246; the hook
// length formula gives 6!/(4.3.2.3.2.1) = 5 and deg Gr(2,5) = 6! 0! 1!/(3! 4!) = 5.)
MOTIF('rectSYT', (() => {
  // All standard Young tableaux of the 2 x 3 rectangle, generated by placing
  // 1..6 one at a time (row 0 first); yields 123/456, 124/356, 125/346, 134/256, 135/246.
  const T = [];
  (function gen(rows, n) {
    if (n > 6) { T.push(rows.map(r => r.slice())); return; }
    for (let r = 0; r < 2; r++) {
      if (rows[r].length < 3 && (r === 0 || rows[0].length > rows[1].length)) {
        rows[r].push(n); gen(rows, n + 1); rows[r].pop();
      }
    }
  })([[], []], 1);
  const N = T.length; // 5

  return {
    draw(ctx, hot, p, k, env, box) {
      const { C, F, U, rgba, clamp, lerp, ease } = env;

      // Timeline (fractions of p; on the 1.875 s card a beat is 0.25).
      const FILL0 = 0.03, FILLD = 0.024;            // numbers 1..6 enter (a quick ripple)
      const DF = 0.05;                              // flip duration
      // Tableaux #2..#5 land on triplet eighths, the last one exactly on beat two.
      const LAND = [0.25, 0.25 + 1 / 12, 0.25 + 2 / 12, 0.5];
      const FLIPS = LAND.map(l => l - DF);
      const flipQ = i => clamp((p - FLIPS[i]) / DF); // progress of flip i (-> tableau i+1)
      const fan = ease.inOut(clamp((p - 0.5) / 0.25)); // the pile fans out after the count
      // Recount: card j's edge lights at RC[j] (back to front, front card on beat three).
      const RC = Array.from({ length: N }, (_, j) => 0.5625 + j * 0.046875);
      const rc = j => { const u = p - RC[j]; return u < 0 ? 0 : Math.exp(-u * 16); };

      // Depth of card j (0 = front) as a continuous quantity.
      const depth = j => { let d = 0; for (let i = j; i < FLIPS.length; i++) d += ease.out(flipQ(i)); return d; };
      const visible = j => j === 0 || flipQ(j - 1) > 0;
      const top = (() => { let t = 0; for (let i = 0; i < FLIPS.length; i++) if (flipQ(i) > 0) t = i + 1; return t; })();

      // Layout: pile on the left, counter on the right; the framing follows the group
      // as it grows (tableau alone -> + counter -> + buried cards -> fanned pile).
      // Sized so the whole group fills ~85% of the box height or ~90% of its width.
      const drift = 1 + 0.025 * ease.soft(clamp((p - 0.45) / 0.55));  // slow push-in after the count
      const s = Math.min(box.w * 0.92 / 5.3, box.h * 0.84 / 2.78) / 1.025 * drift * (1 + 0.015 * k);
      const sp = s * 0.13 * (1 + 0.45 * fan);       // pile offset
      const cs = s * 1.55;                          // counter font size
      const gap = s * 0.55, cw = cs * 0.55;
      const A = ease.inOut(clamp((p - 0.12) / 0.12)), D = depth(0) * sp;
      const x0 = box.x + box.w / 2 - (3 * s + A * (gap + cw) - D) / 2; // front card top-left
      const y0 = box.y + box.h / 2 - (2 * s - D) / 2 - s * 0.04;
      const lw = Math.max(1.5, Math.min(3, s * 0.014));

      const cardRect = j => {
        const d = depth(j);
        let x = x0 - d * sp, y = y0 - d * sp, sc = 1;
        if (j > 0) sc = lerp(1.18, 1, ease.out(clamp(flipQ(j - 1) * 1.4)));
        const w = 3 * s * sc, h = 2 * s * sc;
        x += (3 * s - w) / 2; y += (2 * s - h) / 2;
        return { x, y, w, h, sc };
      };

      // One cell (house Young-diagram style), optional label {t, a, sc} and amber flash fl.
      const cell = (px, py, w, a, lw, lab, fl) => {
        ctx.globalAlpha = a; ctx.strokeStyle = rgba(C.ink, 0.92); ctx.lineWidth = lw;
        ctx.strokeRect(px + 1.5, py + 1.5, w - 3, w - 3); ctx.globalAlpha = 1;
        if (!lab) return;
        // Flash: tinted cell + glowing digit. The hot fill stays low so it never
        // washes out the digit drawn underneath it.
        if (fl > 0) {
          const m = Math.max(2, w * 0.03);
          ctx.fillStyle = rgba(C.amber, 0.16 * fl * a); ctx.fillRect(px + m, py + m, w - 2 * m, w - 2 * m);
          hot.fillStyle = rgba(C.amber, 0.12 * fl * a); hot.fillRect(px + 1.5 * m, py + 1.5 * m, w - 3 * m, w - 3 * m);
        }
        const col = rgba(C.ink.map((v, i) => Math.round(lerp(v, C.amber[i], fl))), 1);
        const sz = w * 0.5 * lab.sc, tx = px + w / 2, ty = py + w / 2 + sz * 0.36, fnt = `${sz}px ${F.main}`;
        U.text(ctx, lab.t, tx, ty, fnt, col, 'center', 'alphabetic', a * lab.a);
        if (fl > 0) U.text(hot, lab.t, tx, ty, fnt, rgba(C.amber, 0.25 * fl), 'center', 'alphabetic', a * lab.a);
      };
      const card = (c, a, lw, label, flash) => {
        const w = s * c.sc;
        for (let r = 0; r < 2; r++) for (let q = 0; q < 3; q++)
          cell(c.x + q * w, c.y + r * w, w, a, lw, label ? label(r, q) : null, flash ? flash(r, q) : 0);
      };
      // Amber outline of a whole card (the recount), on both layers.
      const edge = (c, a) => {
        if (a < 0.02) return;
        for (const g of [ctx, hot]) {
          g.save(); g.globalAlpha = a * (g === hot ? 0.55 : 0.95); g.strokeStyle = rgba(C.amber, 1); g.lineWidth = lw * 1.25;
          g.strokeRect(c.x + 1.5, c.y + 1.5, c.w - 3, c.h - 3); g.restore();
        }
      };

      // ---- the pile, back to front (only edges of buried cards show) -------------
      for (let j = 0; j <= top; j++) {
        if (!visible(j)) continue;
        const c = cardRect(j), d = depth(j), front = j === top;
        ctx.save(); hot.save();
        if (!front) { // clip away the card directly in front of this one
          const f = cardRect(j + 1);
          for (const g of [ctx, hot]) {
            g.beginPath(); g.rect(box.x - box.w, box.y - box.h, 3 * box.w, 3 * box.h); g.rect(f.x, f.y, f.w, f.h); g.clip('evenodd');
          }
        }
        if (j === 0 && top === 0) {
          // build: cells pop in, then 1..6 enter in standard (row-reading) order
          for (let r = 0; r < 2; r++) for (let q = 0; q < 3; q++) {
            const qa = U.stagger(p, r * 3 + q, 6, 0, 0.08, 0.5);
            if (qa <= 0) continue;
            const sc = U.pop(qa), cx = c.x + q * s + s / 2, cy = c.y + r * s + s / 2;
            const n = T[0][r][q], tn = FILL0 + FILLD * (n - 1), qn = clamp((p - tn) / 0.04);
            ctx.save(); ctx.translate(cx, cy); ctx.scale(sc, sc); ctx.translate(-cx, -cy);
            cell(c.x + q * s, c.y + r * s, s, clamp(qa * 2), lw,
              qn > 0 ? { t: String(n), a: clamp(qn * 2), sc: lerp(1.5, 1, ease.out(qn)) } : null,
              qn > 0 ? 1 - clamp((p - tn) / 0.12) : 0);
            ctx.restore();
          }
        } else if (front) {
          const prev = j > 0 ? T[j - 1] : null, a = j > 0 ? clamp(flipQ(j - 1) * 5) : 1;
          const fl = prev ? 1 - clamp((p - FLIPS[j - 1]) / 0.12) : 0;
          card(c, a, lw, (r, q) => ({ t: String(T[j][r][q]), a: 1, sc: 1 }),
            (r, q) => (prev && prev[r][q] !== T[j][r][q] ? fl : 0));
          if (j === N - 1) edge(c, rc(j));
        } else {
          ctx.globalAlpha = Math.max(0.3, 0.85 - 0.15 * d); ctx.strokeStyle = rgba(C.ink, 0.92); ctx.lineWidth = lw * 0.8;
          ctx.strokeRect(c.x + 1.5, c.y + 1.5, c.w - 3, c.h - 3); ctx.globalAlpha = 1;
          edge(c, rc(j));
        }
        ctx.restore(); hot.restore();
      }

      // ---- odometer counter -----------------------------------------------------
      const ccx = x0 + 3 * s + gap + cw / 2, base = y0 + s + cs * 0.34;
      const appear = ease.out(clamp((p - 0.15) / 0.06)); // count starts once 6 has landed
      if (appear > 0) {
        let val = 1, roll = 1;
        FLIPS.forEach((f, i) => { if (p >= f) { val = i + 2; roll = ease.out(clamp((p - f) / (DF * 0.9))); } });
        const amb = val === N ? clamp((p - FLIPS[N - 2]) / DF) : 0; // final 5 turns amber
        const hgt = cs * 1.15, pulse = 1 + 0.05 * k * amb + 0.04 * rc(N - 1);
        const font = `${cs}px ${F.main}`;
        [ctx, hot].forEach(g => {
          if (g === hot && amb <= 0) return;
          g.save();
          g.beginPath(); g.rect(ccx - cw, base - cs * 0.9, cw * 2, cs * 0.97); g.clip();
          g.translate(ccx, base - cs * 0.34); g.scale(pulse, pulse); g.translate(-ccx, -(base - cs * 0.34));
          if (g === ctx && roll < 1) U.text(g, String(val - 1), ccx, base - roll * hgt, font, rgba(C.ink, 1), 'center', 'alphabetic', Math.pow(1 - roll, 1.5) * appear);
          // hot copy kept low: a strong one clips the bloom from amber to lemon yellow
          const col = g === hot ? rgba(C.amber, (0.2 + 0.05 * k) * amb) : rgba(C.ink.map((v, i) => Math.round(lerp(v, C.amber[i], amb))), 1);
          U.text(g, String(val), ccx, base + (1 - roll) * hgt + (1 - appear) * hgt * 0.4, font, col, 'center', 'alphabetic', appear);
          g.restore();
        });
        // label under the counter, once the count is complete
        const la = ease.out(clamp((p - 0.5) / 0.08));
        if (la > 0) {
          const ls = s * 0.25; // scales with the box: a fixed floor overflows the finale-wall tiles
          U.text(ctx, 'deg Gr(2,5)', ccx, base + ls * 2.1 + (1 - la) * ls * 0.6, `${ls}px ${F.main}`, rgba(C.ink, 0.72), 'center', 'alphabetic', la);
        }
      }
    },
  };
})());
