// Schubert (1886): the number of 2-planes in C^5 meeting 6 general 3-planes is
// #SYT(3,3) = deg Gr(2,5) = 5.  A 2x3 rectangle fills with 1..6 in standard order,
// then the motif slaps down every standard Young tableau of shape (3,3) onto a
// pile while an odometer counter rolls 1 -> 5 (the final 5 glows amber).
MOTIF('rectSYT', {
  draw(ctx, hot, p, k, env, box) {
    const { C, F, U, rgba, clamp, lerp, ease } = env;

    // All standard Young tableaux of the 2 x 3 rectangle, generated by placing
    // 1..6 one at a time (row 0 first); yields 123/456, 124/356, 125/346, 134/256, 135/246.
    const T = [];
    (function gen(rows, n) {
      if (n > 6) { T.push(rows.map(r => r.slice())); return; }
      for (let r = 0; r < 2; r++) {
        if (rows[r].length < 3 && (r === 0 || rows[0].length > rows[1].length)) {
          rows[r].push(n); gen(rows, n + 1); rows[r].pop();
        }
      }
    })([[], []], 1);
    const N = T.length; // 5

    // Timeline (fractions of p).
    const FILL0 = 0.07, FILL1 = 0.26;             // numbers 1..6 enter
    const FLIPS = [0.40, 0.50, 0.60, 0.70];       // tableau #2..#5 land on the pile
    const DF = 0.07;                              // flip duration
    const flipQ = i => clamp((p - FLIPS[i]) / DF); // progress of flip i (-> tableau i+1)

    // Depth of card j (0 = front) as a continuous quantity.
    const depth = j => { let d = 0; for (let i = j; i < FLIPS.length; i++) d += ease.out(flipQ(i)); return d; };
    const visible = j => j === 0 || flipQ(j - 1) > 0;
    const top = (() => { let t = 0; for (let i = 0; i < FLIPS.length; i++) if (flipQ(i) > 0) t = i + 1; return t; })();

    // Layout: pile on the left, counter on the right. The framing follows the
    // group as it grows (tableau alone -> + counter -> + buried cards).
    const s = Math.min(box.w / 6.4, box.h / 3.7) * (1 + 0.02 * k);
    const sp = s * 0.13 * (1 + 0.15 * ease.soft(clamp((p - 0.74) / 0.26))); // pile offset, slowly fans out
    const cs = s * 1.55;                          // counter font size
    const gap = s * 0.75, cw = cs * 0.55;
    const A = ease.inOut(clamp((p - 0.22) / 0.16)), D = depth(0) * sp;
    const x0 = box.x + box.w / 2 - (3 * s + A * (gap + cw) - D) / 2; // front card top-left
    const y0 = box.y + box.h / 2 - (2 * s - D) / 2 - s * 0.04;

    const cardRect = j => {
      const d = depth(j);
      let x = x0 - d * sp, y = y0 - d * sp, sc = 1;
      if (j > 0) sc = lerp(1.18, 1, ease.out(clamp(flipQ(j - 1) * 1.4)));
      const w = 3 * s * sc, h = 2 * s * sc;
      x += (3 * s - w) / 2; y += (2 * s - h) / 2;
      return { x, y, w, h, sc };
    };

    // One cell (house Young-diagram style), optional label {t, a, sc} and amber flash fl.
    const cell = (px, py, w, a, lw, lab, fl) => {
      ctx.globalAlpha = a; ctx.strokeStyle = rgba(C.ink, 0.92); ctx.lineWidth = lw;
      ctx.strokeRect(px + 1.5, py + 1.5, w - 3, w - 3); ctx.globalAlpha = 1;
      if (!lab) return;
      if (fl > 0) {
        ctx.fillStyle = rgba(C.amber, 0.16 * fl * a); ctx.fillRect(px + 4, py + 4, w - 8, w - 8);
        hot.fillStyle = rgba(C.amber, 0.38 * fl * a); hot.fillRect(px + 6, py + 6, w - 12, w - 12);
      }
      const col = rgba(C.ink.map((v, i) => Math.round(lerp(v, C.amber[i], fl))), 1);
      const sz = w * 0.5 * lab.sc;
      U.text(ctx, lab.t, px + w / 2, py + w / 2 + sz * 0.36, `${sz}px ${F.main}`, col, 'center', 'alphabetic', a * lab.a);
    };
    const card = (c, a, lw, label, flash) => {
      const w = s * c.sc;
      for (let r = 0; r < 2; r++) for (let q = 0; q < 3; q++)
        cell(c.x + q * w, c.y + r * w, w, a, lw, label ? label(r, q) : null, flash ? flash(r, q) : 0);
    };

    // ---- the pile, back to front (only edges of buried cards show) -------------
    for (let j = 0; j <= top; j++) {
      if (!visible(j)) continue;
      const c = cardRect(j), d = depth(j), front = j === top;
      ctx.save(); hot.save();
      if (!front) { // clip away the card directly in front of this one
        const f = cardRect(j + 1);
        ctx.beginPath(); ctx.rect(box.x, box.y, box.w, box.h); ctx.rect(f.x, f.y, f.w, f.h); ctx.clip('evenodd');
      }
      if (j === 0 && top === 0) {
        // build: cells pop in, then 1..6 enter in standard (row-reading) order
        for (let r = 0; r < 2; r++) for (let q = 0; q < 3; q++) {
          const qa = U.stagger(p, r * 3 + q, 6, 0, 0.12, 0.5);
          if (qa <= 0) continue;
          const sc = U.pop(qa), cx = c.x + q * s + s / 2, cy = c.y + r * s + s / 2;
          const n = T[0][r][q], tn = FILL0 + (FILL1 - FILL0) * (n - 1) / 5, qn = clamp((p - tn) / 0.05);
          ctx.save(); ctx.translate(cx, cy); ctx.scale(sc, sc); ctx.translate(-cx, -cy);
          cell(c.x + q * s, c.y + r * s, s, clamp(qa * 2), 2.2,
            qn > 0 ? { t: String(n), a: clamp(qn * 2), sc: lerp(1.5, 1, ease.out(qn)) } : null,
            qn > 0 ? 1 - clamp((p - tn) / 0.16) : 0);
          ctx.restore();
        }
      } else if (front) {
        const prev = j > 0 ? T[j - 1] : null, a = j > 0 ? clamp(flipQ(j - 1) * 5) : 1;
        const fl = prev ? 1 - clamp((p - FLIPS[j - 1]) / 0.16) : 0;
        card(c, a, 2.2, (r, q) => ({ t: String(T[j][r][q]), a: 1, sc: 1 }),
          (r, q) => (prev && prev[r][q] !== T[j][r][q] ? fl : 0));
      } else {
        ctx.globalAlpha = Math.max(0.3, 0.85 - 0.15 * d); ctx.strokeStyle = rgba(C.ink, 0.92); ctx.lineWidth = 1.8;
        ctx.strokeRect(c.x + 1.5, c.y + 1.5, c.w - 3, c.h - 3); ctx.globalAlpha = 1;
      }
      ctx.restore(); hot.restore();
    }

    // ---- odometer counter -----------------------------------------------------
    const ccx = x0 + 3 * s + gap + cw / 2, base = y0 + s + cs * 0.34;
    const appear = ease.out(clamp((p - FILL1 - 0.05) / 0.07)); // count starts once 6 has landed
    if (appear > 0) {
      let val = 1, roll = 1;
      FLIPS.forEach((f, i) => { if (p >= f) { val = i + 2; roll = ease.out(clamp((p - f) / (DF * 0.9))); } });
      const amb = val === N ? clamp((p - FLIPS[N - 2]) / DF) : 0; // final 5 turns amber
      const hgt = cs * 1.15, pulse = 1 + 0.04 * k * amb;
      const font = `${cs}px ${F.main}`;
      [ctx, hot].forEach(g => {
        if (g === hot && amb <= 0) return;
        g.save();
        g.beginPath(); g.rect(ccx - cw, base - cs * 0.9, cw * 2, cs * 0.97); g.clip();
        g.translate(ccx, base - cs * 0.34); g.scale(pulse, pulse); g.translate(-ccx, -(base - cs * 0.34));
        if (g === ctx && roll < 1) U.text(g, String(val - 1), ccx, base - roll * hgt, font, rgba(C.ink, 1), 'center', 'alphabetic', Math.pow(1 - roll, 1.5) * appear);
        const col = g === hot ? rgba(C.amber, 0.55 * amb) : rgba(C.ink.map((v, i) => Math.round(lerp(v, C.amber[i], amb))), 1);
        U.text(g, String(val), ccx, base + (1 - roll) * hgt + (1 - appear) * hgt * 0.4, font, col, 'center', 'alphabetic', appear);
        g.restore();
      });
      // label under the counter
      const ls = Math.max(16, s * 0.26);
      U.text(ctx, 'deg Gr(2,5)', ccx, base + ls * 2.1, `${ls}px ${F.main}`, rgba(C.ink, 0.62), 'center', 'alphabetic', appear);
    }
  },
});
