// Timeline content. Each entry sits on the music's beat grid:
//   b   : start beat (index into BEATS.beats, may be fractional)
//   len : length in beats
//   era : 'classical' | 'revolution' | 'modern'   (colour story)
//   kind: 'hero' (full-screen) | 'card' | 'flash'
// Citations: [authors, title, venue · year]. Verified list (see README for sources).
window.ENTRIES = [
  { b: 0, len: 8, kind: 'hero', era: 'classical', year: 1879, name: 'Enumerative calculus', motif: 'lines4',
    cites: [['H. Schubert', 'Kalkül der abzählenden Geometrie', 'Teubner, Leipzig · 1879']] },
  { b: 8, len: 2, era: 'classical', year: 1886, name: 'Degree of the Grassmannian', motif: 'rectSYT',
    cites: [['H. Schubert', 'Anzahl-Bestimmungen für lineare Räume beliebiger Dimension', 'Acta Math. 8 · 1886']] },
  { b: 10, len: 2, era: 'classical', year: 1893, name: 'Pieri rule', motif: 'pieri',
    cites: [['M. Pieri', 'Sul problema degli spazi secanti', 'Rend. Ist. Lombardo · 1893']] },
  { b: 12, len: 2, era: 'classical', year: 1900, name: "Hilbert's 15th problem", motif: 'hilbert',
    cites: [['D. Hilbert', 'Mathematische Probleme', 'ICM Paris · 1900']] },
  { b: 14, len: 2, era: 'classical', year: 1902, name: 'Giambelli formula', motif: 'giambelli',
    cites: [['G. Z. Giambelli', 'Risoluzione del problema degli spazi secanti', 'Mem. R. Accad. Sci. Torino · 1902']] },
  { b: 16, len: 2, era: 'classical', year: 1934, name: 'Schubert cells', motif: 'cells',
    cites: [['C. Ehresmann', 'Sur la topologie de certains espaces homogènes', 'Ann. of Math. 35 · 1934']] },
  { b: 18, len: 2, era: 'classical', year: 1934, name: 'Littlewood–Richardson rule', motif: 'lr',
    cites: [['D. E. Littlewood, A. R. Richardson', 'Group characters and algebra', 'Phil. Trans. R. Soc. A 233 · 1934']] },
  { b: 20, len: 2, era: 'classical', year: 1947, name: 'Schur functions', motif: 'lesieur',
    cites: [['L. Lesieur', "Les problèmes d'intersection sur une variété de Grassmann", 'C. R. Acad. Sci. Paris 225 · 1947']] },
  { b: 22, len: 2, era: 'classical', year: 1959, name: 'Monk formula', motif: 'monk',
    cites: [['D. Monk', 'The geometry of flag manifolds', 'Proc. London Math. Soc. 9 · 1959']] },
  { b: 24, len: 2, era: 'revolution', year: 1973, name: 'Divided differences', motif: 'divdiff',
    cites: [['I. N. Bernstein, I. M. Gelfand, S. I. Gelfand', 'Schubert cells and cohomology of the spaces G/P', 'Russian Math. Surveys 28 · 1973'],
      ['M. Demazure', 'Désingularisation des variétés de Schubert généralisées', 'Ann. Sci. ÉNS 7 · 1974']] },
  { b: 26, len: 2, era: 'revolution', year: 1977, name: 'Jeu de taquin', motif: 'jdt',
    cites: [['M.-P. Schützenberger', 'La correspondance de Robinson', 'LNM 579 · 1977']] },
  { b: 32, len: 4, kind: 'hero', era: 'revolution', year: 1982, name: 'Schubert polynomials', motif: 'schubpoly',
    cites: [['A. Lascoux, M.-P. Schützenberger', 'Polynômes de Schubert', 'C. R. Acad. Sci. Paris 294 · 1982']] },
  { b: 36, len: 2, era: 'revolution', year: 1984, name: 'Stanley symmetric functions', motif: 'wiring',
    cites: [['R. P. Stanley', 'On the number of reduced decompositions of elements of Coxeter groups', 'European J. Combin. 5 · 1984'],
      ['P. Edelman, C. Greene', 'Balanced tableaux', 'Adv. Math. 63 · 1987']] },
  { b: 38, len: 2, era: 'revolution', year: 1992, name: 'Essential set', motif: 'rothe',
    cites: [['W. Fulton', 'Flags, Schubert polynomials, degeneracy loci, and determinantal formulas', 'Duke Math. J. 65 · 1992']] },
  { b: 40, len: 4, era: 'revolution', year: 1993, name: 'Pipe dreams', motif: 'pipedream',
    cites: [['S. Billey, W. Jockusch, R. P. Stanley', 'Some combinatorial properties of Schubert polynomials', 'J. Algebraic Combin. 2 · 1993'],
      ['N. Bergeron, S. Billey', 'RC-graphs and Schubert polynomials', 'Experiment. Math. 2 · 1993']] },
  { b: 44, len: 2, era: 'revolution', year: 1997, name: 'Quantum Schubert calculus', motif: 'quantum',
    cites: [['A. Bertram', 'Quantum Schubert calculus', 'Adv. Math. 128 · 1997'],
      ['S. Fomin, S. Gelfand, A. Postnikov', 'Quantum Schubert polynomials', 'J. Amer. Math. Soc. 10 · 1997']] },
  { b: 46, len: 1, era: 'revolution', year: 1999, name: 'Honeycombs & saturation', motif: 'honeycomb',
    cites: [['A. Knutson, T. Tao', 'The honeycomb model of GLn(C) tensor products I', 'J. Amer. Math. Soc. 12 · 1999']] },
  { b: 47, len: 1, era: 'modern', year: 2002, name: 'K-theoretic LR rule', motif: 'setvalued',
    cites: [['A. S. Buch', 'A Littlewood–Richardson rule for the K-theory of Grassmannians', 'Acta Math. 189 · 2002']] },
  { b: 48, len: 4, kind: 'hero', era: 'modern', year: 2003, name: 'Puzzles', motif: 'puzzle',
    cites: [['A. Knutson, T. Tao', 'Puzzles and (equivariant) cohomology of Grassmannians', 'Duke Math. J. 119 · 2003']] },
  { b: 52, len: 2, era: 'modern', year: 2005, name: 'Gröbner geometry', motif: 'groebner',
    cites: [['A. Knutson, E. Miller', 'Gröbner geometry of Schubert polynomials', 'Ann. of Math. 161 · 2005']] },
  { b: 54, len: 2, era: 'modern', year: 2006, name: 'Checkers', motif: 'checkers',
    cites: [['R. Vakil', 'A geometric Littlewood–Richardson rule', 'Ann. of Math. 164 · 2006']] },
  { b: 56, len: 1, era: 'modern', year: 2008, name: 'Affine Schubert calculus', motif: 'affine',
    cites: [['T. Lam', 'Schubert polynomials for the affine Grassmannian', 'J. Amer. Math. Soc. 21 · 2008']] },
  { b: 57, len: 1, era: 'modern', year: 2009, name: 'Shapiro conjecture', motif: 'real',
    cites: [['E. Mukhin, V. Tarasov, A. Varchenko', 'The B. and M. Shapiro conjecture in real algebraic geometry…', 'Ann. of Math. 170 · 2009']] },
  { b: 58, len: 1, era: 'modern', year: 2016, name: 'Two-step puzzles', motif: 'puzzle2',
    cites: [['A. Buch, A. Kresch, K. Purbhoo, H. Tamvakis', 'The puzzle conjecture for the cohomology of two-step flag manifolds', 'J. Algebraic Combin. 44 · 2016']] },
  { b: 59, len: 1, era: 'modern', year: 2019, name: 'Schubitopes', motif: 'polytope',
    cites: [['A. Fink, K. Mészáros, A. St. Dizier', 'Schubert polynomials as integer point transforms…', 'Adv. Math. 332 · 2018']] },
  { b: 60, len: 1, era: 'modern', year: 2021, name: 'Bumpless pipe dreams', motif: 'bpd',
    cites: [['T. Lam, S. J. Lee, M. Shimozono', 'Back stable Schubert calculus', 'Compositio Math. 157 · 2021']] },
  { b: 61, len: 1, era: 'modern', year: 2022, name: 'Log-concavity', motif: 'logconcave',
    cites: [['J. Huh, J. Matherne, K. Mészáros, A. St. Dizier', 'Logarithmic concavity of Schur and related polynomials', 'Trans. AMS 375 · 2022']] },
  { b: 62, len: 1, era: 'modern', year: 2024, name: 'Regularity', motif: 'regularity',
    cites: [['O. Pechenik, D. Speyer, A. Weigandt', 'Castelnuovo–Mumford regularity of matrix Schubert varieties', 'Selecta Math. · 2024']] },
];
window.FINALE = {
  question: 'A positive combinatorial rule for every',
  formula: 'c_{u,v}^{w}',
  status: 'Still open.',
  title: 'Schubert Calculus',
  span: '1879 — today',
};
